/**
 * Sentinel AI - Scan History Logic
 */

const historyBody = document.getElementById('history-body');
const searchInput = document.getElementById('search-input');
const clearBtn = document.getElementById('clear-btn');

function renderHistory() {
    const history = SentinelState.getHistory();
    const searchTerm = searchInput.value.toLowerCase();

    // clear table
    historyBody.innerHTML = '';

    const filtered = history.filter(item =>
        item.filename.toLowerCase().includes(searchTerm)
    );

    if (filtered.length === 0) {
        historyBody.innerHTML = '<tr><td colspan="5" style="text-align:center; color:#666;">No logs found.</td></tr>';
        return;
    }

    filtered.forEach(item => {
        const tr = document.createElement('tr');

        const date = new Date(item.timestamp).toLocaleString();
        const statusClass = item.is_malware ? 'status-critical' : 'status-safe';
        const statusText = item.is_malware ? 'Critical' : 'Safe';

        tr.innerHTML = `
            <td>${date}</td>
            <td>${item.filename}</td>
            <td>${item.threat_score}</td>
            <td class="${statusClass} font-weight-bold">${statusText}</td>
            <td>
                <button class="btn-download" onclick="downloadReport('${item.id}')">
                    <i class="fa-solid fa-download"></i> Report
                </button>
            </td>
        `;
        historyBody.appendChild(tr);
    });
}

function downloadReport(id) {
    const history = SentinelState.getHistory();
    const item = history.find(i => i.id === id);
    if (!item) return;

    const reportContent = `
Sentinel AI - Scan Report
-------------------------
Scan ID: ${item.id}
Date: ${new Date(item.timestamp).toLocaleString()}
Filename: ${item.filename}
Status: ${item.is_malware ? 'Critical' : 'Safe'}
Threat Score: ${item.threat_score}/100

Suspicious Imports:
${item.detected_imports ? item.detected_imports.join('\n') : 'None'}

-------------------------
Generated by Sentinel AI
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Report_${item.filename}.txt`;
    a.click();
    URL.revokeObjectURL(url);
}

// Make downloadReport global so onclick works
window.downloadReport = downloadReport;

// Event Listeners
searchInput.addEventListener('input', renderHistory);

clearBtn.addEventListener('click', () => {
    if (confirm('Are you sure you want to clear all scan logs? This action cannot be undone.')) {
        SentinelState.clearHistory();
        renderHistory();
    }
});

// Initial Render
renderHistory();
